// Generated by `agentcomm hooks --harness opencode` — commit it so every
// OpenCode session in this repo joins the bus. Safe to edit; regenerating
// never overwrites an existing file.
//
// Drives the globally installed agentcomm CLI
// (npm install -g https://github.com/yonidavidson/agentcomm/releases/latest/download/agentcomm-latest.tgz).
// Every hook fails open: a broken bus never wedges the session.
import type { Plugin } from '@opencode-ai/plugin';

export const AgentcommHooks: Plugin = async ({ directory, client, $ }) => {
  const sh = $.cwd(directory).nothrow();

  // Session start: register on the repo bus (auto-detected from the git
  // remote) under a session-unique alias.
  await sh`agentcomm register --status "opencode session"`.quiet();

  return {
    // OpenCode's session.idle can't block, so the inbox guard degrades to a
    // nudge: unread mail re-prompts the session instead of holding it open.
    async event({ event }) {
      if (event.type !== 'session.idle') return;
      const sessionID = (event as { properties?: { sessionID?: string } }).properties?.sessionID;
      if (!sessionID) return;
      const peek = await sh`agentcomm peek --json`.quiet();
      let unread: unknown[] = [];
      try {
        unread = JSON.parse(peek.text() || '[]');
      } catch {
        return; // off the bus, or the CLI is missing — fail open
      }
      if (!Array.isArray(unread) || unread.length === 0) return;
      await client.session
        .prompt({
          path: { id: sessionID },
          body: {
            parts: [
              {
                type: 'text',
                text: `agentcomm: ${unread.length} unread message(s) — run "agentcomm inbox --json", handle them, then continue.`,
              },
            ],
          },
        })
        .catch(() => {});
    },
  };
};

export default AgentcommHooks;
