// Generated by `agentcomm hooks --harness opencode` — commit it so every
// OpenCode session in this repo joins the bus. Safe to edit; regenerating
// never overwrites an existing file.
//
// Drives the globally installed agentcomm CLI (npm install -g @yonidavidson/agentcomm@latest).
// Every hook fails open: a broken bus never wedges the session.
import type { Plugin } from '@opencode-ai/plugin';

export const AgentcommHooks: Plugin = async ({ directory, client, $ }) => {
  const sh = $.cwd(directory).nothrow();

  // Telemetry parity with Claude Code/Codex: normalize the harness payload
  // and hand it to the CLI, which owns the repo's telemetry.track rule
  // matching (inert without a telemetry config).
  const telemetry = (payload: Record<string, unknown>) =>
    sh`echo ${JSON.stringify(payload)} | agentcomm hook telemetry`.quiet();

  // Session start: register on the repo bus (auto-detected from the git
  // remote) under a session-unique alias.
  await sh`agentcomm register --status "opencode session"`.quiet();
  await telemetry({ hook_event_name: 'SessionStart' });

  return {
    // Tracked tool events → the CLI's rule matcher. Only the tools the rules
    // can name; bash is pre-filtered so ordinary commands never spawn a CLI.
    async 'tool.execute.after'(input) {
      const args = (input as { args?: Record<string, unknown> }).args ?? {};
      if (input.tool === 'skill' && typeof args.name === 'string') {
        await telemetry({ hook_event_name: 'PostToolUse', tool_name: 'Skill', tool_input: { skill: args.name } });
      } else if (input.tool === 'task' && typeof args.subagent_type === 'string') {
        await telemetry({ hook_event_name: 'PostToolUse', tool_name: 'Task', tool_input: { subagent_type: args.subagent_type } });
      } else if (input.tool === 'bash' && typeof args.command === 'string' && args.command.includes('merge')) {
        await telemetry({ hook_event_name: 'PostToolUse', tool_name: 'Bash', tool_input: { command: args.command } });
      }
    },
    // OpenCode's session.idle can't block, so the inbox guard degrades to a
    // nudge: unread mail re-prompts the session instead of holding it open.
    async event({ event }) {
      if (event.type !== 'session.idle') return;
      const sessionID = (event as { properties?: { sessionID?: string } }).properties?.sessionID;
      if (!sessionID) return;
      const peek = await sh`agentcomm peek --json`.quiet();
      let unread: unknown[] = [];
      try {
        unread = JSON.parse(peek.text() || '[]');
      } catch {
        return; // off the bus, or the CLI is missing — fail open
      }
      if (!Array.isArray(unread) || unread.length === 0) return;
      await client.session
        .prompt({
          path: { id: sessionID },
          body: {
            parts: [
              {
                type: 'text',
                text: `agentcomm: ${unread.length} unread message(s) — run "agentcomm inbox --json", handle them, then continue.`,
              },
            ],
          },
        })
        .catch(() => {});
    },

    // Session end is the last chance to ship the local event spool.
    async dispose() {
      await telemetry({ hook_event_name: 'SessionEnd' });
      await sh`agentcomm emit --flush`.quiet();
    },
  };
};

export default AgentcommHooks;
